version: '3.9'

services:
  # MongoDb services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  # Backend services
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment: 
      - PORT=3000
      - MONGO_URL=mongodb://mongo_db:27017
      - TOKEN_SECRET=mysecretkey
      - COOKIE_SECRET=DLKSFLK(*&(*&&*^&*KJHH878678
      - SPORTMONK_API_TOKEN=cHGem9ZQ147ZZF2zdNK0AxTO6y3kaxbHQdg0ieavmXFCLj4KLJtLThGiXOX3
      - PRODUCTION=false
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
